version: '2.1'

services:

  redis:
    restart: unless-stopped
    image: redis
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass 1234
    
  rq:
    build:
      context: ./rq/
    restart: unless-stopped
    image: rq
    volumes:
      - ./app:/app
    command: rq worker --burst low high medium -u redis://:1234@redis:6379/10
    
  dashboard:
    build:
      context: ./rq/
    ports:
      - "9181:9181"
    restart: unless-stopped
    image: dashboard
    command: rq-dashboard -u redis://:1234@redis:6379/10
    
    
    

  
