version: '2.1'

services:

  redis:
    restart: unless-stopped
    image: redis
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"

    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ['redis-server', '--requirepass $${REDIS_PASSWORD}']
